conditional_labelling_split_folder: "/datasets/home/hbenoit/label-cond-as/"
conditional_labelling_split_name_format: "s_{split_semantic_task_idx}_d_{split_spurious_task_idx}_conditional_labelling_split_0.5.torch"
train_val_split_folder: "/datasets/home/hbenoit/label-cond-as/"
train_val_split_name_format: "s_{split_semantic_task_idx}_d_{split_spurious_task_idx}_train_val_split_0.5.torch"
discovered_tasks_path: "/datasets/home/hbenoit/adversarial-splits/assets/tasks/discovered.csv"



batch_size_train: 512 
batch_size_eval: 512 
seed: 0 
epochs: 60 
lr: 0.001
opt: "sgd" 
scheduler: "none" 
alpha: 0.2
perturb_type: "ood_is_test" 
model: "resnet18" 
dataset: "cifar-10" 
eval_freq: 500
l2_reg: 0.0001
